language: generic
sudo: false

env:
  global:
    - BYOND_MAJOR=513
    - BYOND_MINOR=1528

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

before_install:
  - chmod +x -R scripts/
  - chmod +x test/run-test.sh

script:
  - test/run-test.sh

matrix:
  include:
    - name: "DreamChecker"
      env: SPACEMAN_DMM_VERSION=suite-1.5
      cache:
        directories: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
      install:
        - ./scripts/install-spaceman-dmm.sh dreamchecker
      script:
        - ~/dreamchecker

    - name: "Code and Map Linting"
      env: TEST=LINTING
      addons:
        apt:
          packages:
            - python3.5

    - name: "Unit Tests - Box Station"
      env: 
        - TEST=UNIT
        - MAP_NAME="Box Station"
        - MAP_META=boxstation
      install:
        - ./scripts/install-byond.sh
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
      addons:
        apt:
          packages:
            - libstdc++6:i386

    - name: "Unit Tests - Gamma Station"
      env: 
        - TEST=UNIT
        - MAP_NAME="Gamma Station"
        - MAP_META=gamma
      install:
        - ./scripts/install-byond.sh
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
      addons:
        apt:
          packages:
            - libstdc++6:i386

    - name: "Compile Everything"
      env: TEST=COMPILE
      install:
        - ./scripts/install-byond.sh
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
      addons:
        apt:
          packages:
            - libstdc++6:i386
