language: generic
sudo: false

env:
  global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1463"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python3.5

before_script:
  - chmod +x -R scripts/
  - chmod +x test/run-test.sh
  - ./scripts/install-byond.sh
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup

script:
  - test/run-test.sh
