# https://github.com/actions/stale

name: 'Close stale issues and PRs'
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3.0.19
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: >
            Данный ПР автоматически отмечен как застоявшийся по причине длительного отсутствия обновлений.
            Он будет закрыт через 7 дней, если никакой активности не будет проявлено.
            Если вы считаете, что ПР еще актуален, или что я (злобный робот) пристаю к вам зря - просто напишите любой комментарий.
            Спасибо за ваш вклад.
          close-pr-message: >
            ПР закрыт из-за длительного отсуствия активности. Для переоткрытия ПРа, пожалуйста, обратитесь к
            кому-либо из мейнтейнеров. Вы можете призвать их в комментарии слапнув ``@TauCetiStation/maintainers``.
          exempt-pr-labels: 'Pinned, Awaiting Review [Translation Dep], Awaiting Review [Sprite Dep]'
          stale-pr-label: 'Stalled PR'
          days-before-pr-stale: 7
          days-before-pr-close: 7
          close-issue-message:  >
            Данное предложение пробыло без активности открытым более полугода. Если вы найдёте того, кто его реализует,
            и вам нужно открыть данный ишью, пожалуйста, обратитесь к кому-либо из мейнтейнеров.
            Вы можете призвать их в комментарии слапнув ``@TauCetiStation/maintainers``.
          exempt-issue-labels: 'Bug'
          days-before-issue-stale: 200
          days-before-issue-close: 1
          stale-issue-label: "Stalled Proposal"
